---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class
  namespace: default
allowVolumeExpansion: true
mountOptions:
- option
parameters:
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
volumeBindingMode: Immediate
