---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pod-disruption-budget
  namespace: default
spec:
  maxUnavailable: 1
  minAvailable: 1
  selector:
    matchLabels:
      app: nginx
