---
apiVersion: v1
kind: PodTemplate
metadata:
  name: pod-template
  namespace: default
template:
  metadata:
    labels:
      app: pod-template
  spec:
    containers:
    - command:
      - echo
      - hello
      image: nginx
      name: container
