---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: default
spec:
  limits:
  - type: Pod
    default:
      cpu: 100m
      memory: 100Mi
    defaultRequest:
      cpu: 100m
      memory: 100Mi
    max:
      cpu: 1
      memory: 1Gi
    maxLimitRequestRatio:
      cpu: 10
      memory: 10
    min:
      cpu: 100m
      memory: 100Mi
