---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: custom-resource-definition
  namespace: default
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        caBundle:
        - 1
        - 2
        - 3
        service:
          name: webhook-service
          namespace: default
          path: /convert
        url: https://webhook-service.default.svc:443/convert
      conversionReviewVersions:
      - v1
  group: example.com
  names:
    kind: Example
    listKind: ExampleList
    plural: examples
    singular: example
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              replicas:
                type: integer
                format: int32
          status:
            type: object
            properties:
              replicas:
                type: integer
                format: int32
    served: true
    storage: true
