---
apiVersion: v1
kind: ReplicationController
metadata:
  name: replication-controller
  namespace: default
spec:
  minReadySeconds: 1
  replicas: 1
  selector:
    app: replication-controller
  template:
    metadata:
      labels:
        app: replication-controller
    spec:
      containers:
      - command:
        - echo
        - hello
        image: nginx
        name: container
