---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helm-release
  namespace: flux-system
spec:
  chart:
    spec:
      chart: my-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: my-helm-repo
        namespace: my-namespace
      version: 1.0.0
  interval: 10m0s
