---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    key: value
  labels:
    key: value
  name: helm-release
  namespace: default
spec:
  interval: 10m
  dependsOn:
  - name: dependency1
    namespace: default
  chart:
    spec:
      chart: my-chart
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: my-helm-repo
  values:
    key: value
