---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helm-release
spec:
  interval: 10m
  chart:
    spec:
      chart: my-chart
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: my-helm-repo
